server:
port: 8086

jpa:
defer-datasource-initialization: true
hibernate:
ddl-auto: none

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:notifications
    username: sa
    password:
  driverClassName: org.h2.Driver