server:
  port: 8086

jpa:
  defer-datasource-initialization: true
  hibernate:
    ddl-auto: none

spring:
  application:
    name: notify-micro-service
  datasource:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
liquibase:
  enabled: true
  drop-first: false
  default-schema: public
